# Generated by Django 5.0.4 on 2024-04-21 07:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100, verbose_name='место')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время')),
                ('action', models.CharField(max_length=255, verbose_name='действие')),
                ('is_good_habit', models.BooleanField(blank=True, default=False, null=True, verbose_name='признак приятной привычки')),
                ('periodic', models.IntegerField(default='1', verbose_name='периодичность')),
                ('lead_time', models.IntegerField(blank=True, null=True, verbose_name='время выполнения')),
                ('is_public', models.BooleanField(default=False, verbose_name='публичный')),
                ('reward', models.CharField(blank=True, max_length=255, null=True, verbose_name='награда')),
                ('associated_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits_tracker.habit', verbose_name='связанная привычка')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
            },
        ),
    ]
