# Generated by Django 5.0.4 on 2024-04-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits_tracker', '0006_habit_date_last_send'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='periodic',
            field=models.CharField(choices=[('0', 'Раз в неделю'), ('1', 'Два раза в неделю'), ('2', 'Три раза в неделю'), ('3', 'Четыре раза в неделю'), ('4', 'Пять раз в неделю'), ('5', 'Шесть раз в неделю'), ('6', 'Семь раз в неделю')], max_length=20, verbose_name='периодичность'),
        ),
    ]
