# Generated by Django 5.0.4 on 2024-04-27 10:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits_tracker', '0007_alter_habit_periodic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='periodic',
            field=models.CharField(choices=[('1', 'Каждый день'), ('2', 'Каждые 2 дня'), ('3', 'Каждые 3 дня'), ('4', 'Каждые 4 дня'), ('5', 'Каждые 5 дней'), ('6', 'Каждые 6 дней'), ('7', 'Раз в неделю')], max_length=20, verbose_name='периодичность'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='время'),
        ),
    ]
