# Generated by Django 5.0.4 on 2024-04-27 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits_tracker', '0008_alter_habit_periodic_alter_habit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='date_last_send',
            field=models.DateField(default=datetime.datetime.today, verbose_name='дата последней отправки'),
        ),
    ]
