version: "3"

services:
  db:
    image: postgres:16-alpine
#    restart: always
    env_file:
      - .env
    expose:
      - '5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - PGDATA=/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER" ]
      interval: 5s
      timeout: 15s
      retries: 5

  app:
    build: .
    tty: true
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    depends_on:
      - db

  # REDIS
  redis:
    image: redis
    ports:
      - '6379:6379'

  # CELERY
  celery:
    build: .
    tty: true
    command: celery -A drf_course_work worker -l INFO
    depends_on:
      - redis
      - app

  # CELERY-BEAT
  celery_beat:
    build: .
    tty: true
    command: celery -A drf_course_work beat -l INFO -S django
    depends_on:
      - redis
      - app


volumes:
  pg_data:





